dataset:
  sampling_length: 128
  f0_glob: "/path/to/f0/*.npy"
  phoneme_glob: "/path/to/phoneme/*.npy"
  spec_glob: "/path/to/spec/*.npy"
  silence_glob: "/path/to/silence/*.npy"
  speaker_dict_path: "/path/to/speaker_dict_path.json"
  num_speaker: 100
  test_num: 100
  test_trial_num: 10

network:
  input_feature_size: 40
  output_size: 80
  speaker_size: 100
  speaker_embedding_size: 16
  decoder_hidden_size: 128
  decoder_layer_num: 4

model:
  eliminate_silence: true

train:
  batch_size: 32
  log_iteration: 1000
  snapshot_iteration: 20000
  stop_iteration: 500000
  optimizer:
    name: "adam"
    lr: 1.0e-4
  weight_initializer: "orthogonal"

project:
  name: null
  tags: {}
